spring:
  datasource:
    password: 666
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/javaWeb_final_db?characterEncoding=utf-8
  mail:
    host: smtp.qq.com
    username: 1422941961@qq.com
    password: hmkeeupvtbdsiidi
    port: 465
    properties:
      from: 1422941961@qq.com
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

image:
  get-url: https://api.itbaima.net/image/api/v1/upload
  authorization: JBD34XGISA1TEY399M5GGRWCY53NTJ6E